# Generated by Django 5.2 on 2025-04-27 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tasa_desercion', models.FloatField()),
                ('tasa_aprobacion', models.FloatField()),
                ('horario', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'asignatura',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_de_nacimiento', models.DateField()),
                ('promedio_actual', models.FloatField()),
                ('promedio_acumulado', models.FloatField()),
                ('avance', models.FloatField()),
                ('horas_de_dedicacion', models.IntegerField()),
            ],
            options={
                'db_table': 'estudiante',
            },
        ),
        migrations.CreateModel(
            name='Recomendaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=1000)),
            ],
            options={
                'db_table': 'recomendaciones',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('peso', models.FloatField()),
                ('fecha', models.DateField()),
                ('asignatura_id', models.ForeignKey(db_column='asignatura_id', on_delete=django.db.models.deletion.CASCADE, to='api.asignatura')),
            ],
            options={
                'db_table': 'evaluacion',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('usuario', models.EmailField(max_length=100, unique=True)),
                ('contraseña', models.CharField(max_length=100)),
                ('rol_id', models.ForeignKey(db_column='rol_id', on_delete=django.db.models.deletion.CASCADE, to='api.rol')),
            ],
            options={
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='Estres',
            fields=[
                ('estudiante_id', models.OneToOneField(db_column='estudiante_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.estudiante')),
                ('nivel_de_estres', models.FloatField()),
                ('escala_de_accion', models.FloatField()),
                ('recomendaciones_id', models.ForeignKey(db_column='recomendaciones_id', on_delete=django.db.models.deletion.CASCADE, to='api.recomendaciones')),
            ],
            options={
                'db_table': 'estres',
            },
        ),
        migrations.CreateModel(
            name='carga_trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(max_length=100)),
                ('creditos', models.IntegerField()),
                ('asistencia', models.FloatField()),
                ('numero_asignaturas', models.IntegerField()),
                ('horas_dedicadas', models.IntegerField()),
                ('estudiante_id', models.ForeignKey(db_column='estudiante_id', on_delete=django.db.models.deletion.CASCADE, to='api.estudiante')),
            ],
            options={
                'db_table': 'carga_trabajo',
                'unique_together': {('estudiante_id', 'semestre')},
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_asistencia', models.FloatField()),
                ('interacciones_plataforma', models.IntegerField()),
                ('nota', models.FloatField()),
                ('repetida', models.BooleanField(default=False)),
                ('asignatura_id', models.ForeignKey(db_column='asignatura_id', on_delete=django.db.models.deletion.CASCADE, to='api.asignatura')),
                ('estudiante_id', models.ForeignKey(db_column='estudiante_id', on_delete=django.db.models.deletion.CASCADE, to='api.estudiante')),
            ],
            options={
                'db_table': 'asistencia',
                'unique_together': {('estudiante_id', 'asignatura_id')},
            },
        ),
    ]
